FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.24-openshift-4.21 AS builder
WORKDIR /go/src/github.com/metal3-io/ironic-standalone-operator
COPY . .
RUN CGO_ENABLED=0 GO111MODULE=on go build -a -o manager cmd/main.go

# TEST CI

FROM registry.ci.openshift.org/ocp/4.21:base-rhel9
COPY --from=builder /go/src/github.com/metal3-io/ironic-standalone-operator/manager /

ENTRYPOINT ["/manager"]
