FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.25-openshift-4.22 AS builder
WORKDIR /go/src/github.com/metal3-io/ironic-standalone-operator
COPY . .
RUN CGO_ENABLED=0 GO111MODULE=on go build -a -o manager cmd/main.go

FROM registry.ci.openshift.org/ocp/4.22:base-rhel9
COPY --from=builder /go/src/github.com/metal3-io/ironic-standalone-operator/manager /

ENTRYPOINT ["/manager"]
